/**
 * Pre-designed text style templates.
 * Each template provides default text config for a new text clip.
 */
const textTemplates = [
  {
    id: 'title',
    name: 'Title',
    description: 'Large bold centered text',
    text: {
      content: 'Title Text',
      fontFamily: 'Arial',
      fontSize: 72,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
      stroke: false,
      shadow: true,
      shadowColor: '#000000',
      shadowBlur: 8,
      hasBg: false,
      lineHeight: 1.2,
      letterSpacing: 2,
      animation: 'fadeIn',
      animationDuration: 0.8,
    },
    transform: { x: 0, y: 0, scale: 1, rotation: 0 },
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    description: 'Medium text below center',
    text: {
      content: 'Subtitle',
      fontFamily: 'Arial',
      fontSize: 36,
      fontWeight: 'normal',
      color: '#e0e0e0',
      align: 'center',
      stroke: false,
      shadow: true,
      shadowColor: '#000000',
      shadowBlur: 4,
      hasBg: false,
      lineHeight: 1.4,
      letterSpacing: 1,
      animation: 'fadeIn',
      animationDuration: 0.6,
    },
    transform: { x: 0, y: 100, scale: 1, rotation: 0 },
  },
  {
    id: 'lower-third',
    name: 'Lower Third',
    description: 'Name bar at bottom-left',
    text: {
      content: 'Speaker Name',
      fontFamily: 'Helvetica',
      fontSize: 28,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'left',
      stroke: false,
      shadow: false,
      hasBg: true,
      bgColor: '#1a1a2e',
      bgOpacity: 0.85,
      lineHeight: 1.4,
      letterSpacing: 0.5,
      animation: 'slideIn',
      animationDuration: 0.5,
    },
    transform: { x: -350, y: 230, scale: 1, rotation: 0 },
  },
  {
    id: 'caption',
    name: 'Caption',
    description: 'Bottom-center readable text',
    text: {
      content: 'Caption text goes here',
      fontFamily: 'Arial',
      fontSize: 24,
      fontWeight: 'normal',
      color: '#ffffff',
      align: 'center',
      stroke: true,
      strokeColor: '#000000',
      strokeWidth: 2,
      shadow: false,
      hasBg: true,
      bgColor: '#000000',
      bgOpacity: 0.6,
      lineHeight: 1.4,
      letterSpacing: 0,
      animation: 'fadeIn',
      animationDuration: 0.3,
    },
    transform: { x: 0, y: 250, scale: 1, rotation: 0 },
  },
  {
    id: 'watermark',
    name: 'Watermark',
    description: 'Small corner text',
    text: {
      content: 'WATERMARK',
      fontFamily: 'Arial',
      fontSize: 16,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'right',
      stroke: false,
      shadow: false,
      hasBg: false,
      lineHeight: 1,
      letterSpacing: 2,
      animation: 'none',
    },
    transform: { x: 350, y: -250, scale: 1, rotation: 0 },
    opacity: 0.35,
  },
];

export default textTemplates;
